# YAML configuration file for computing settlement at the centerpoint of the foundation
# This code is presently only applicable to computing settlement at the centerpoint of the foundation

#Settlement is estimated from the following equation:

#Settlement:           Î”H = ğ‘ â‹… B'â‹… (1-Î½Â²)/Es â‹… m â‹… ğ¼ğ‘  â‹… ğ¼ğ‘“

#Î”H: Immediate settlement
#ğ‘:  Intensity of contact pressure in units of Es
#B': Least lateral dimension of contributing base area in units of Î”H
#ğ¼ğ‘ : Influence factor, which depends on L'/B', thickness of stratum H, Poisson's ratio Î½
#ğ¼ğ‘“: Influence factor, which depends on embedment depth D
#Es: Elastic settlement modulus
#Î½:  Poisson's ratio  
#m:  Number of contributing base areas

# Specify the embedment depth and shape parameters:
settlement_parameters:
  D: 1.5                   # Foundation depth in feet
  shape: 1                 # L / B ratio to account for footing shape

# Specify the backfill and foundation parameters:
soil_properties:
  gamma_backfill: 125      # Unit weight of structural backfill in pcf
  gamma_soil: 120          # Unit weight of the foundation soil in pcf
  Z: 50                    # Depth to hard layer in feet
  phi: 35                  # Soil friction angle in degrees
  c: 0                     # Soil cohesion in psf
  nu: 0.33                 # Poisson's ratio

# If you want to read in a file with layer information, set modulus_file=True.
# csv file format should contain a row for each layer and have columns named "layer_number", "top", "bottom", "modulus"
# The first layer "top" is at the base of the foundation.
# If modulus_file=False, the constant Es value will be used.

modulus_options:
  modulus_file: true       # Set to true to read layer information from a file
  file: 'layers.csv'       # Path to CSV file containing layer information
  Es: None                 # Constant Settlement Modulus in ksf (used if modulus_file is false)